### ISSUE TITLE
Validation not worked

### ISSUE THREAD

**Issue by shaqqan** [h3llmy/nest-formdata#53]
```
  app.useGlobalInterceptors(
    new FormdataInterceptor({
      customFileName(context, originalFileName) {
        return `${Date.now()}-${originalFileName}`;
      },
      fileSaver: new DefaultFileSaver({
        prefixDirectory: "./storage/public",
        customDirectory(context, originalDirectory) {
          return originalDirectory;
        },
      }),
    })
  )
```

```
import { IsLocale, IsNotEmpty, IsString } from "class-validator";
import {
    FileData,
    HasMimeType,
    IsFileData,
    MaxFileSize,
    MimeType,
    MinFileSize,
} from "nestjs-formdata-interceptor";

export class CreateLanguageDto {
    @IsString()
    name: string;

    @IsLocale()
    locale: string;
    
    @IsFileData()
    @IsNotEmpty()
    @HasMimeType([MimeType["image/jpeg"], MimeType["image/png"], MimeType["image/jpg"]])
    @MaxFileSize(5 * 1024 * 1024)
    // single file
    icon: FileData;
}
```

```
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at <anonymous> (/usr/src/app/node_modules/nestjs-formdata-interceptor/src/validators/hasMimeType.decorator.ts:45:23)
    at Array.some (<anonymous>)
    at HasMimeTypeConstraint.matchesWildcard (/usr/src/app/node_modules/nestjs-formdata-interceptor/src/validators/hasMimeType.decorator.ts:44:21)
    at HasMimeTypeConstraint.validate (/usr/src/app/node_modules/nestjs-formdata-interceptor/src/validators/hasMimeType.decorator.ts:33:19)
    at <anonymous> (/usr/src/app/node_modules/src/validation/ValidationExecutor.ts:271:68)
    at Array.forEach (<anonymous>)
    at <anonymous> (/usr/src/app/node_modules/src/validation/ValidationExecutor.ts:253:82)
    at Array.forEach (<anonymous>)
    at ValidationExecutor.customValidations (/usr/src/app/node_modules/src/validation/ValidationExecutor.ts:252:15)
    at ValidationExecutor.performValidations (/usr/src/app/node_modules/src/validation/ValidationExecutor.ts:212:10)
[Nest] 1109  - 12/30/2024, 10:10:57 AM   ERROR [ExceptionsFilter] TypeError: Cannot read properties of undefined (reading 'endsWith')
```

**Comment by h3llmy** [comment]
This is because there is no type for "MimeType['image/jpg']". You just only need to add "MimeType['image/jpeg']" to allow uploading files with either .jpg or .jpeg extensions.

**Comment by jongomes** [comment]
![Image](https://github.com/user-attachments/assets/387176b2-f73f-445f-ac92-71c6f2737346)

![Image](https://github.com/user-attachments/assets/a3f27ab8-f3e2-49a7-8c75-4afa3b274a8c)

It works with jpeg, but when I send jpg it gives an error

![Image](https://github.com/user-attachments/assets/820532ce-af74-4d42-80bd-12eecc1c7e20)

![Image](https://github.com/user-attachments/assets/e4c3b291-968e-4dbf-917c-4750d4849131)

when I specify each type, it validates correctly, but if I use image/*, it gives an error in startsWith

**Comment by h3llmy** [comment]
> ![Image](https://github.com/user-attachments/assets/387176b2-f73f-445f-ac92-71c6f2737346)
> 
> ![Image](https://github.com/user-attachments/assets/a3f27ab8-f3e2-49a7-8c75-4afa3b274a8c)
> 
> It works with jpeg, but when I send jpg it gives an error
> 
> ![Image](https://github.com/user-attachments/assets/820532ce-af74-4d42-80bd-12eecc1c7e20)
> 
> ![Image](https://github.com/user-attachments/assets/e4c3b291-968e-4dbf-917c-4750d4849131)
> 
> when I specify each type, it validates correctly, but if I use image/*, it gives an error in startsWith

can you disable the validation and log the request body

it should displaying like this on terminal:
```
{
  file: FileData {
    originalFileName: '19ce4743-bcdd-4eb7-807b-e35206a33887-1.sketchpad.jpeg',
    fileName: '1743044796315-19ce4743-bcdd-4eb7-807b-e35206a33887-1.sketchpad',
    fileNameFull: '1743044796315-19ce4743-bcdd-4eb7-807b-e35206a33887-1.sketchpad.jpeg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    fileExtension: 'jpeg',
    fileSize: 229418,
    hash: '064dc76dccfdef2335064162d748d24a',
    buffer: <Buffer ff d8 ff e0 00 10 4a 46 49 46 00 01 01 01 00 90 00 90 00 00 ff e2 01 d8 49 43 43 5f 50 52 4f 46 49 4c 45 00 01 01 00 00 01 c8 00 00 00 00 04 30 00 00 ... 229368 more bytes>
  }
}
```

when it displaying like this :

```
{
  file: '19ce4743-bcdd-4eb7-807b-e35206a33887-1.sketchpad.jpeg'
}
```

make sure you change the request enctype to ``multipart/form-data`` on your request for sending file to server

**Comment by jongomes** [comment]
Yes, I'm using postman to test, if I remove the validation it works correctly, but I would like it with validation

I believe the problem is in the jpg extension, with jpeg OK

**Comment by h3llmy** [comment]
> Yes, I'm using postman to test, if I remove the validation it works correctly, but I would like it with validation
> 
> I believe the problem is in the jpg extension, with jpeg OK

can you give the request example?
i trying using jpg extension and its work totally fine
```
{
  file: FileData {
    originalFileName: 'IMG20250301152037.jpg',
    fileName: '1743297239364-IMG20250301152037',
    fileNameFull: '1743297239364-IMG20250301152037.jpg',
    encoding: '7bit',
    mimetype: 'image/jpeg',
    fileExtension: 'jpg',
    fileSize: 1945524,
    hash: '56e86ca0b79127c596d4d333a970b7c8',
    buffer: <Buffer ff d8 ff e1 03 04 45 78 69 66 00 00 49 49 2a 00 08 00 00 00 08 00 0f 01 02 00 05 00 00 00 6e 00 00 00 10 01 02 00 11 00 00 00 74 00 00 00 1a 01 05 00 ... 1945474 more bytes>
  }
}
```

**Comment by jongomes** [comment]
The problem is actually when it doesn't send the property in the form-data

For example, you expect file, and postman doesn't send it, it breaks when image/*, but it doesn't break when it's image/jpeg

![Image](https://github.com/user-attachments/assets/97799a85-3563-4b81-808b-62ab951b3902)

https://codesandbox.io/p/devbox/dazzling-austin-f8s2x5

![Image](https://github.com/user-attachments/assets/9471db98-03cf-44db-9731-085cd8fca873)

so @IsNotEmpty() is not caught

**Comment by h3llmy** [comment]
> The problem is actually when it doesn't send the property in the form-data
> 
> For example, you expect file, and postman doesn't send it, it breaks when image/*, but it doesn't break when it's image/jpeg
> 
> ![Image](https://github.com/user-attachments/assets/97799a85-3563-4b81-808b-62ab951b3902)
> 
> https://codesandbox.io/p/devbox/dazzling-austin-f8s2x5
> 
> ![Image](https://github.com/user-attachments/assets/9471db98-03cf-44db-9731-085cd8fca873)
> 
> so [@isnotempty](https://github.com/isnotempty)() is not caught

okay i find the problem, #58 this pr fixed that bug and published to version 1.3.5

**Comment by jongomes** [comment]
Work me, close issue

**Comment by jongomes** [comment]
![Image](https://github.com/user-attachments/assets/e774fba2-3653-456c-8892-b3947ff0346e)

The request is fluctuating when it is in .jpg format, I have to send it 3 times for it to work

![Image](https://github.com/user-attachments/assets/eab1f689-220d-406c-9dd9-14b894dc388b)

**Comment by h3llmy** [comment]
> ![Image](https://github.com/user-attachments/assets/e774fba2-3653-456c-8892-b3947ff0346e)
> 
> The request is fluctuating when it is in .jpg format, I have to send it 3 times for it to work
> 
> ![Image](https://github.com/user-attachments/assets/eab1f689-220d-406c-9dd9-14b894dc388b)

how do i get that error?

**Comment by jongomes** [comment]
Image not work. Áudio ok
